version: '3.8'

services:
  # Servicio MongoDB
  mongodb:
    image: mongo:latest
    container_name: leadhub8-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=leadhub8
    networks:
      - leadhub8-network

  # Servicio Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: leadhub8-backend
    restart: unless-stopped
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app/server
      - ./ecosystem.config.js:/app/ecosystem.config.js
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/leadhub8
      - PORT=3000
      - CLIENT_URL=http://localhost:5173
    networks:
      - leadhub8-network
    command: ["pm2-runtime", "ecosystem.config.js"]

  # Servicio Frontend
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: leadhub8-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    networks:
      - leadhub8-network

# Volúmenes
volumes:
  mongodb_data:
    driver: local

# Redes
networks:
  leadhub8-network:
    driver: bridge 